### ISSUE TITLE
Milestone 2 - Select 6 features as functional requirements that you will implement.

### ISSUE THREAD

**Issue by dogfriendbookclub** [dogfriendbookclub/Application#15]

**Comment by dogfriendbookclub** [comment]
[Project Milestone 2 - 01.pdf](https://github.com/user-attachments/files/16859029/Project.Milestone.2.-.01.pdf)

**Comment by Chang-Vang** [comment]
These are the six features we came up during class.

1. Searching Function
2. Submitting Reviews
3. Mark Favorites/Favorites List
4. User’s Profile
5. Adding Reactions to Reviews
6. Logging/Authentications Users

**Comment by Nicholas2501** [comment]
Search Feature:
Actors: Users, Database API
Primary Actor: User
Goal: The goal of this feature is to return the results the user is searching for.
Basic Flow: The user enters a title of a show, the database API takes the search parameter and returns the show which matches the name of the title that the user is searching for. 
Alternative Flow: The show is not in the database in which the application pops up a screen which says "Show is not found".

**Comment by dogfriendbookclub** [comment]
> These are the six features we came up during class.
> 
> 1. Searching Function
> 2. Submitting Reviews
> 3. Mark Favorites/Favorites List
> 4. User’s Profile
> 5. Adding Reactions to Reviews
> 6. Logging/Authentications Users

Update to 1:
Search by cast, director or another attribute that is not the TV show name

Update to 2:
Ability to bookmark reviews to read for later

**Comment by PaulTrevizo** [comment]
> Search Feature: Actors: Users, Database API Primary Actor: User Goal: The goal of this feature is to return the results the user is searching for. Basic Flow: The user enters a title of a show, the database API takes the search parameter and returns the show which matches the name of the title that the user is searching for. Alternative Flow: The show is not in the database in which the application pops up a screen which says "Show is not found".

I made a couple of updates to this,

Made small change to Actors:
Users & Database API

Changed the Use Case Goal:
To return the search results based on the criteria specified by the user

Added Preconditions:
The user will have entered a search keyword or keywords in the fixed search bar located at the top of the application.

**Comment by dogfriendbookclub** [comment]
I think we're good to close this one out
