### ISSUE TITLE
Milestone 2 - Updates to Requirements.md

### ISSUE THREAD

**Issue by dogfriendbookclub** [dogfriendbookclub/Application#18]
- A list of 3 non-functional requirements. For each non-functional
requirement, describe in detail how your application will comply with that
requirement. 

- 6 Use Case Descriptions. Use the template in Specification.md to describe 3
use cases.

- 1 use case diagram.

[Project Milestone 2 - 01.pdf](https://github.com/user-attachments/files/16859042/Project.Milestone.2.-.01.pdf)

**Comment by Chang-Vang** [comment]
Added has a list of 3 non-functional requirements and 6 use case descriptions adhering to the template given.

Non-functional Requirements
1. Data Integrity
2. Transparency
3. Quality

Use Cases:
1. Search Function (By actors, tv-show)
2. Submitting Reviews
3. Mark Favorites/Favorites List
4. Adding reactions to reviews
5. User Login/Authentication
6. User Profile Management

(Not Completed): Still need diagram

**Comment by PaulTrevizo** [comment]
Hi Team, thank you for your patience. Here is my draft of the use cases that Chang made. Would you please take a look and let me know what you'd like me to update?
![Use Case Diagram_DRAFT](https://github.com/user-attachments/assets/e06cddae-4a2c-454a-b116-ed5737302aa9)

**Comment by Nicholas2501** [comment]
The diagram is looking great @PaulTrevizo. I think this is good for the milestone. I can't find anything else needed to be added.

**Comment by caLeb-centy** [comment]
Looks good paul 🙏

**Comment by PaulTrevizo** [comment]
Thank you all. The diagram is now committed to Requirements.md

**Comment by PaulTrevizo** [comment]
Chang and Paul completed this task.

**Comment by PaulTrevizo** [comment]
Chang and Paul completed this task.
