### ISSUE TITLE
Milestone 2 - Updates to Entities.md

### ISSUE THREAD

**Issue by dogfriendbookclub** [dogfriendbookclub/Application#19]
- List the entities in your application.

- Describe what each entity does

[Project Milestone 2 - 01.pdf](https://github.com/user-attachments/files/16859049/Project.Milestone.2.-.01.pdf)

**Comment by Nicholas2501** [comment]
List of entities in our program:
The User - Our primary customer that can create reviews, view reviews and even have their own section of favorite shows.
Database API - This API is the tool used to grab information about shows from the database we use.
Shows - this is a list of shows available for users to look at.
Reviews - Reviews for shows in which other users can read and view.
Favorites tab - This section would be a screen in which a user will be able to see a list of shows they have favorited in their individual user profile.

**Comment by Nicholas2501** [comment]
Added my file from my branch with a list of possible entities and descriptions of what they do in our program
