### ISSUE TITLE
Milestone 2 - Update CHANGELOG

### ISSUE THREAD

**Issue by dogfriendbookclub** [dogfriendbookclub/Application#21]

**Comment by dogfriendbookclub** [comment]
hey everyone!

when you do something this week just leave a comment here and when i update the changelog at the end of the week, i can check here for what everyone did.

**Comment by Chang-Vang** [comment]
Added has a list of 3 non-functional requirements and 6 use case descriptions adhering to the template given.

Non-functional Requirements
1. Data Integrity
2. Transparency
3. Quality

Use Cases:
1. Search Function (By actors, tv-show)
2. Submitting Reviews
3. Mark Favorites/Favorites List
4. Adding reactions to reviews
5. User Login/Authentication
6. User Profile Management

Although not completed: still need a use-case diagram to be embedded into Requirements.md

**Comment by Nicholas2501** [comment]
Created the Entities file and added all the information in the file for the entities User class, Database API, Search Engine, Review Class, Shows Class, Screen entities. Also added the user description of the search engine for the requirements file.
