### ISSUE TITLE
Milestone 3 - Implement Reviewable, Likable and MediaType

### ISSUE THREAD

**Issue by dogfriendbookclub** [dogfriendbookclub/Application#31]
Implement all of the code in your class diagram including the models, views, and
controllers you identified in the first part of this milestone

From: [Project Milestone 3 - 01.pdf](https://github.com/user-attachments/files/17036648/Project.Milestone.3.-.01.pdf)

**Comment by PaulTrevizo** [comment]
Commited Likable Interface and MediaType enum. Still working to finalize Reviewable interface.

**Comment by PaulTrevizo** [comment]
@dogfriendbookclub question for you. The UML diagram dictates that there is a toString operation in Reviewable, but toString is already available to all objects. Do you think we still need it? Here is a copy of my code:

```
package edu.metrostate;

public interface Reviewable {
    //"public" declaration is not needed as methods in interfaces are understood to be public

    double getStars();
    int getShowId();
    void recalculateStars(Reviewable reviewable);

    //is toString necessary in the interface?
    //void toString();
}
```

**Comment by PaulTrevizo** [comment]
Hi everyone! Reviewable is now committed.

Thank you Bryn!
