### ISSUE TITLE
Milestone 3 - Implement Show, Season, and Episode

### ISSUE THREAD

**Issue by dogfriendbookclub** [dogfriendbookclub/Application#32]
Implement all of the code in your class diagram including the models, views, and
controllers you identified in the first part of this milestone

From: [Project Milestone 3 - 01.pdf](https://github.com/user-attachments/files/17036648/Project.Milestone.3.-.01.pdf)

**Comment by dogfriendbookclub** [comment]
![rottenPotatoesUML_v2](https://github.com/user-attachments/assets/7d333ee1-bff2-4dd0-ae32-a09e3fbd11a1)

**Comment by Nicholas2501** [comment]
I have created the classes for show, season, and episode along with testing to ensure it prints the information. I think it needs more improvement but I have pushed the commits to my branch. Will look into making the Scenes and Stages to see if it displays the information how we want it to look. Will implement view and control later in the week!

**Comment by Nicholas2501** [comment]
Created the classes with the addition of a few extra classes because of the way the API is set up. Also made a few tweaks on variables because it seemed like too much information for the given class it was in. API works as intended when pulling information and filling out variables.
