### ISSUE TITLE
Milestone 3 - Create JavaFX Views 

### ISSUE THREAD

**Issue by dogfriendbookclub** [dogfriendbookclub/Application#38]
"You will need to create JavaFX views as part of this milestone, but they are not required to be functional. In other words, I will not be executing the code turned in for the milestone. The assessment will be based on the quality of your MVC design and the accuracy of your code implementation of your design"

[Project Milestone 3 - 01.pdf](https://github.com/user-attachments/files/17036716/Project.Milestone.3.-.01.pdf)

**Comment by Chang-Vang** [comment]
Created HomePage.fxml, ShowOverview.fxml, and their controllers. Not too sure if you guys can run the GUI on your machines.

**Comment by Chang-Vang** [comment]
Created the rest of the .fxml files that were apart of the wireframes; SeasonOverview, EpisodeOverview, and SearchPage. Created a controller for each page.

All work was done through the SceneBuilder Application.

**Comment by Chang-Vang** [comment]
Will continue to develop JavaFX pages (.fxml) as we move forward with the final vision of the product.
