### ISSUE TITLE
Create wire frames for each screen in your application.

### ISSUE THREAD

**Issue by dogfriendbookclub** [dogfriendbookclub/Application#5]
[Project Milestone 1 - 01.pdf](https://github.com/user-attachments/files/16775845/Project.Milestone.1.-.01.pdf)

**Comment by Nicholas2501** [comment]
Creating a rough outline for what our Home Screen will look like. Let me know if anyone else wants any changes.
<img width="3268" alt="Welcome to FigJam" src="https://github.com/user-attachments/assets/cda27711-4890-4e77-8a29-c72a289bbb95">

**Comment by PaulTrevizo** [comment]
@Nicholas2501 what did you use to create this wireframe? I just want to mimic your style as much as possible for the show-specific wireframe for the sake of consistency

**Comment by PaulTrevizo** [comment]
Hi everyone, here is my wireframe for the show-specific screen. I envisioned a drop-down where the user can select the overall show, or a specific season. This one is for the specific season. Let me know what you think. I can make two more (one showing a specific season, and another showing a specific episode, but I wanted to get your feedback on this one first as it will be the basis for the other two.
![Show-Specific Wireframe ft Overall Show Summary](https://github.com/user-attachments/assets/fad8f913-fb2f-4316-aa23-838ef090948b)

**Comment by caLeb-centy** [comment]
looks good, could you add a heart to the left of "your show rating" with the text "like"

**Comment by PaulTrevizo** [comment]
> looks good, could you add a heart to the left of "your show rating" with the text "like"

How is this?
![Show-Specific Wireframe ft Overall Show Summary_v2](https://github.com/user-attachments/assets/b5efb3bc-fa1f-4678-8adf-3f245a4f40d4)

**Comment by caLeb-centy** [comment]
looks good

**Comment by caLeb-centy** [comment]
![Search screen](https://github.com/user-attachments/assets/1f832983-0fc9-41a9-9477-73b672eefbde)

here is a wire frame of the search screen,  lmk any feedback pls

**Comment by Nicholas2501** [comment]
Sorry for the late reply but both of your wireframes look really good. Looks a lot better than my simplistic one. I should look into vennage because it looks like it has more detailed options.

**Comment by PaulTrevizo** [comment]
> Sorry for the late reply but both of your wireframes look really good. Looks a lot better than my simplistic one. I should look into vennage because it looks like it has more detailed options.

@Nicholas2501 it's been pretty simple so far. 

Also, I made the other two wireframes. It's the same screen, but it changes depending on the user's selection of the home button/season selector/episode selector. Please let me know your thoughts on this.
![Show-Specific Wireframe ft Overall Show Summary_v3 0](https://github.com/user-attachments/assets/1aa0b027-c47c-4905-a6d8-c543ce1f439f)
![Show-Specific Wireframe ft Overall Show Summary_v3 1](https://github.com/user-attachments/assets/1d3d8542-fbc3-4402-812a-fed622b58435)
![Show-Specific Wireframe ft Overall Show Summary_v3 2](https://github.com/user-attachments/assets/ccd0abd6-b1da-42e5-aab5-26b5fe32e78b)

**Comment by Nicholas2501** [comment]
@PaulTrevizo it's looking really good and I like the idea of keeping it simple with having the screens of episodes and seasons being the same with the selection. The little highlight on the selector to tell and overview in big bold is good for letting people know what section/review they are viewing.

**Comment by dogfriendbookclub** [comment]
thanks everyone for getting those together! i'm going to go ahead and close this issue out.
