### ISSUE TITLE
Milestone 4 - Update UML Documentation

### ISSUE THREAD

**Issue by dogfriendbookclub** [dogfriendbookclub/Application#61]
https://lucid.app/lucidchart/cca8b55a-5048-4e97-a657-9aad87574e94/edit?viewport_loc=-3060%2C-4460%2C3497%2C2278%2CHWEp-vi-RSFO&invitationId=inv_35bccc27-3ce5-4fc3-8df0-eab07cb42ba5
@PaulTrevizo  if you can't access this link let me know

**Comment by PaulTrevizo** [comment]
Hi @dogfriendbookclub, I added the classes in pink. Would you mind being a second set of eyes to make sure the connections are correct? --- FYI, I haven't checked the existing classes for missing methods yet.
![UML class (1)](https://github.com/user-attachments/assets/943e8d61-4a47-41af-b3dd-114f82b5a79a)
